CREATE TABLE donations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    receipt_number VARCHAR(100) UNIQUE,
    donor_name VARCHAR(255) NOT NULL,
    donor_address TEXT,
    pan_number VARCHAR(10),
    donor_phone VARCHAR(20),
    donor_email VARCHAR(255),
    amount DECIMAL(15, 2) NOT NULL,
    payment_mode_id BIGINT NOT NULL,
    purpose_id BIGINT NOT NULL,
    sub_category_id BIGINT,
    event_id BIGINT,
    branch_id BIGINT NOT NULL,
    donation_date DATE NOT NULL,
    notes TEXT,
    receipt_generated BOOLEAN DEFAULT FALSE,
    receipt_generated_at TIMESTAMP NULL,
    receipt_file_path VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMP NULL,
    deleted_by BIGINT NULL,
    FOREIGN KEY (payment_mode_id) REFERENCES payment_modes(id) ON DELETE RESTRICT,
    FOREIGN KEY (purpose_id) REFERENCES donation_purposes(id) ON DELETE RESTRICT,
    FOREIGN KEY (sub_category_id) REFERENCES donation_sub_categories(id) ON DELETE SET NULL,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL,
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_receipt_number (receipt_number),
    INDEX idx_donor_name (donor_name),
    INDEX idx_pan_number (pan_number),
    INDEX idx_donation_date (donation_date),
    INDEX idx_branch_id (branch_id),
    INDEX idx_purpose_id (purpose_id),
    INDEX idx_event_id (event_id),
    INDEX idx_payment_mode_id (payment_mode_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

